[nope]
long_enter = -60
long_exit  = -30
short_enter = 50
short_exit  = 35
call_limit = 5
put_limit = 5
call_quantity = 1
put_quantity = 1
expiry_offset = 2
call_strike_offset = 1
put_strike_offset = 1

set_stop_loss = true

[debug]
enabled = false

[tda]
token_path = ""
api_key = ""
redirect_uri = ""
account_id = ""
