[nope]
# Enter and exit NOPE thresholds
long_enter = -60
long_exit  = -30
short_enter = 45
short_exit  = 30

# Reversions are unlikely at very low/high NOPE. Do not trade below/above these limits
long_enter_limit = -90
short_enter_limit = 70

# Buy contracts up to the configured limit
call_limit = 5
put_limit = 5

# How many contracts to buy per order
call_quantity = 1
put_quantity = 1

# Automatically select optimal contract to buy
contract_auto_select = true
# Min. DTE offset for auto-select
auto_min_dte = 1
# Delta to aim for with auto-select, recommend 30 for auto_min_dte = 0, 60 for auto_min_dte > 0
auto_target_delta = 60

# Manual DTE setting to use when contract_auto_select is false, 0 is same day expiry, higher is later dates
expiry_offset = 2

# Manual strike price setting to use when contract_auto_select is false, 0 is ATM, higher is OTM (10 max)
# ATM/OTM only for manual
call_strike_offset = 1
put_strike_offset = 1

# Cut losses at this return
stop_loss_percentage = 20

# Cancel unfilled orders older than the set minutes
minutes_cancel_unfilled = 5

[debug]
enabled = false
verbose = false

[ib]
# Used to check account balance before buys, leave empty to skip checking
account = ""

[tda]
token_path = ""
api_key = ""
redirect_uri = ""
account_id = ""
