[nope]
long_enter = -60
long_exit  = -30
short_enter = 30
short_exit  = 15
call_limit = 5
put_limit = 5
call_quantity = 1
put_quantity = 1
expiry_offset = 2
call_strike_offset = 1
put_strike_offset = 1

[debug]
enabled = false
